name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./aimodel/pom.xml
          mvn clean package -f ./map/pom.xml
          mvn clean package -f ./data/pom.xml
          mvn clean package -f ./statistic/pom.xml
          mvn clean package -f ./summary/pom.xml
          mvn clean package -f ./dashboard/pom.xml

      - name: Docker Build and push for Aimodel
        uses: docker/build-push-action@v4
        with:
          context: ./aimodel
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/aimodel:latest
            ghcr.io/${{ github.repository }}/aimodel:${{ github.ref_name }}
            
      - name: Docker Build and push for Map
        uses: docker/build-push-action@v4
        with:
          context: ./map
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/map:latest
            ghcr.io/${{ github.repository }}/map:${{ github.ref_name }}
            
      - name: Docker Build and push for Data
        uses: docker/build-push-action@v4
        with:
          context: ./data
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/data:latest
            ghcr.io/${{ github.repository }}/data:${{ github.ref_name }}
            
      - name: Docker Build and push for Statistic
        uses: docker/build-push-action@v4
        with:
          context: ./statistic
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/statistic:latest
            ghcr.io/${{ github.repository }}/statistic:${{ github.ref_name }}
            
      - name: Docker Build and push for Summary
        uses: docker/build-push-action@v4
        with:
          context: ./summary
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/summary:latest
            ghcr.io/${{ github.repository }}/summary:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
