server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: aimodel
          uri: http://localhost:8082
          predicates:
            - Path=/aiModels/**, 
        - id: map
          uri: http://localhost:8083
          predicates:
            - Path=/maps/**, 
        - id: modeldata
          uri: http://localhost:8084
          predicates:
            - Path=/riskData/**, /srcData/**, 
        - id: statistic
          uri: http://localhost:8085
          predicates:
            - Path=/statistics/**, 
        - id: summary
          uri: http://localhost:8086
          predicates:
            - Path=/summaries/**, 
        - id: dashboard
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: aimodel
          uri: http://aimodel:8080
          predicates:
            - Path=/aiModels/**, 
        - id: map
          uri: http://map:8080
          predicates:
            - Path=/maps/**, 
        - id: modeldata
          uri: http://modeldata:8080
          predicates:
            - Path=/riskData/**, /srcData/**, 
        - id: statistic
          uri: http://statistic:8080
          predicates:
            - Path=/statistics/**, 
        - id: summary
          uri: http://summary:8080
          predicates:
            - Path=/summaries/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
